{% set name = 'plingo' %}
{% set dev = not environ.get('BUILD_RELEASE', false) %}
{% set version = environ.get('VERSION_NUMBER') %}
{% set revision = environ.get('GITHUB_SHA', 'wip') %}
{% set build = environ.get('BUILD_NUMBER', "0") %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../..

requirements:
  host:
  - python >=3.7
  - pip
  run:
  - clingo>=5.5

build:
  number: {{ build }}
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points: ['plingo = plingo:main']


about:
  home: https://potassco.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A system for probabilistic reasoning in clingo
  doc_url: https://github.com/potassco/{{ name }}
  dev_url: https://github.com/potassco/{{ name }}
